apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: craftista-ingress
  namespace: app
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb   # 🔥 THIS IS MANDATORY
  rules:
  - host: evoqu.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
