apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: craftista-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.class: "gce"                # Use GCE ingress controller
      #networking.gke.io/managed-certificates: "craftista-cert"  # Optional, for managed TLS cert
spec:
  rules:
  - host: app.abhinanilkumar.online                      # Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
              targetPort: 3000

